url: https://tjmichk.github.io
baseurl: /Digital-Portfolio-Website/

# Site settings
title: Terrence Micciche-Hall
email: tjmichk@gmail.com
description: A clean, modern, one page online portfolio for Terrence Micciche-Hall

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/terrencemiccichehall/
  - title: github
    url: https://github.com/TJMICHK

# Build settings
markdown: kramdown
permalink: pretty